# Site settings
title: Shalit's Life Archive # site title
description: >- # site description
    Archive of Shalit's Online Life.
lang: en-US # default lang
timezone: America/Los_Angeles # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/shalitslife/shalitslife.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Shalit # author name
  bio: >- # tell to the world
      Dlive Streamer, Epic Tweeter and High-Ranking Groyper.
      He passed away on October 9, 2020.
      This is an archive of his streams and tweets among other things.
  username: shalit # general username
  twitter: sh4llot # twitter username
  dlive: shalit # dlive username
  twitch: jmahc # twitch username
  archive: shalit_archive # archive username
  email: shalitslife@protonmail.com # email adress
  avatar: /assets/img/avi.jpg # change with your own avatar

# URL settings
  url: "https://shalits.life/" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: false

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
